---
- name: Setup machine
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Check SSH
      ansible.builtin.command: echo "Connected to node"
      changed_when: false

    - name: Clear cached password
      ansible.builtin.command: sudo -k
      changed_when: false

    - name: Try password out
      register: result
      ignore_errors: true
      become: true
      changed_when: false
      timeout: 1
      ansible.builtin.command: echo "Password is correct"

    - name: Check if password worked
      when: result is failed or result.rc is not defined or result.rc != 0
      ansible.builtin.fail:
        msg: "Invalid password"

    - name: Install base software
      become: true
      ansible.builtin.apt:
        pkg:
          - gnupg2
          - vim

    - name: Install btrfs tools
      become: true
      ansible.builtin.apt:
        pkg:
          - btrfs-progs

- name: Setup repositories
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Import maintainer's public key
      become: true
      ansible.builtin.apt_key:
        id: 4EFC590696CB15B87C73A3AD82CC8797C838DCFD
        url: https://pkgs.zabbly.com/key.asc

    - name: Add Zabbly repository for stable version
      notify: Update apt cache
      become: true
      ansible.builtin.deb822_repository:
        name: zabbly-incus-stable
        types: deb
        uris: https://pkgs.zabbly.com/incus/stable
        suites: "{{ ansible_distribution_release }}"
        components: main
        architectures: amd64
        signed_by: 4EFC590696CB15B87C73A3AD82CC8797C838DCFD

  handlers:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        cache_valid_time: 0

- name: Setup Incus
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Install Incus
      register: install
      become: true
      ansible.builtin.apt:
        name: incus
        install_recommends: false

    - name: Install Incus UI
      become: true
      ansible.builtin.apt:
        name: incus-ui-canonical
        install_recommends: false

    - name: Enable user to manage Incus
      notify: Reconnect session
      register: user_groups
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: incus-admin
        append: true

    - name: Reload groups
      ansible.builtin.meta: flush_handlers

    - name: Set client listen address
      when: install.changed
      notify: Restart Incus
      ansible.builtin.command: incus --force-local config set core.https_address :8443

    - name: Create network
      when: install.changed
      notify: Restart Incus
      ansible.builtin.command: >-
        incus --force-local network create {{ item.key }} --type={{ item.value.type }}
        {% for cfg in item.value.config | default([]) %} {{ cfg }}={{ item.value.config[cfg] }}{% endfor %}
      loop: "{{ incus.network | default({}) | dict2items }}"

    - name: Add default network to default profile
      when: install.changed and (incus.network.default is defined)
      notify: Restart Incus
      ansible.builtin.command: incus --force-local profile device add default eth0 nic network=default name=eth0

    - name: Create storage pool
      when: install.changed
      notify: Restart Incus
      ansible.builtin.command: >-
        incus --force-local storage create {{ item.key }} {{ item.value.driver }}
        {% for cfg in item.value.config | default([]) %} {{ cfg }}={{ item.value.config[cfg] }}{% endfor %}
      loop: "{{ incus.storage | default({}) | dict2items }}"

    - name: Add default storage pool to default profile
      when: install.changed and (incus.storage.default is defined)
      notify: Restart Incus
      ansible.builtin.command: incus --force-local profile device add default root disk path=/ pool=default

  handlers:
    - name: Reconnect session
      ansible.builtin.meta: reset_connection

    - name: Restart Incus
      become: true
      ansible.builtin.systemd:
        name: incus.service
        state: restarted
