[project]
name = "homelab"
version = "0.0.0"
requires-python = ">=3.12.11"
readme = "README.md"
dependencies = [
    "passlib>=1.7.4",
]

[project.urls]
Repository = "https://github.com/bruno-delfino1995/homelab"
