#!/usr/bin/env bash

#USAGE about="Encrypt a value through ansible-vault"
#USAGE arg "<value>" help="String to encrypt for your vault"

set -euo pipefail
IFS=$'\n\t'

DIR=$(realpath "$(dirname "$0")")

cd "$DIR" || exit 1

./guarded ansible-vault encrypt_string --vault-password-file=/bin/cat "$1"
