#!/usr/bin/env bash

#USAGE about="Execute anything in a specific host"
#USAGE arg "<cmd>" var=#true help="Command to send to target host"

set -euo pipefail
IFS=$'\n\t'

DIR=$(realpath "$(dirname "$0")")

cd "$DIR" || exit 1

HOST="$1"
shift

printf -v IN_CMD '%q ' "$@"
printf -v CMD '%q ' bash -c "$IN_CMD"

./guarded ansible "$HOST" --vault-password-file=/bin/cat -m ansible.builtin.shell -b -a "$CMD"
