---
- name: Check SSH
  ansible.builtin.command: echo "Connected to node"
  changed_when: false

- name: Clear cached password
  ansible.builtin.command: sudo -k
  changed_when: false

- name: Try password out
  register: result
  ignore_errors: true
  become: true
  changed_when: false
  timeout: 5
  ansible.builtin.command: echo "Password is correct"

- name: Check if password worked
  when: result is failed or result.rc is not defined or result.rc != 0
  ansible.builtin.fail:
    msg: "Invalid password"
